### PR TITLE
Completed Read Functionality Card

### PR DESCRIPTION
**Pull request by jennerdulce**

### CODE REVIEW

**Review by WalkerTexas-coder — CHANGES_REQUESTED** [review]
What's going on with the folders structure?

**Comment by Renzlawr** [comment]
> What's going on with the folders structure?

@jennerdulce and I ended up creating folders that contain the component and their tests and or css together, is there a more preferred method in this case?

**Comment by WalkerTexas-coder** [comment]
IME its an unnecessary level of organization but I'm down to let it roll if you like it.

**Comment by Renzlawr** [comment]
> IME its an unnecessary level of organization but I'm down to let it roll if you like it.

Might think about changing it to have our pages directory, and add a tests directory and a stylesheets directory. Just to remove any confusion around it

**Review by WalkerTexas-coder — APPROVED** [review]
Let's go!

**Pull request merged**
